(() => {
 'use strict';
 const $ = (s,root=document) => root.querySelector(s);
 const all = (s,root=document) => [...root.querySelectorAll(s)];
 const data = window.AMINOS, groups = window.GROUPS, key='amino-lab-v1';
 const clean = v => String(v).trim().toLowerCase().replace(/\s+/g,' ');
 const esc = v => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let progress={},storageOK=true;
 try { const parsed=JSON.parse(localStorage.getItem(key)||'{}'); if(parsed && typeof parsed==='object' && !Array.isArray(parsed)) progress=parsed; } catch { storageOK=false; }
 let view='practice', filter='all', bonus=false, paper=false, current=data[0], revealed=false, graded=false, structureScore=null, queue=[], index=0, exam=null, strokes=[], redo=[], activeStroke=null, canvas=null, ctx=null, observer=null;
 const mistakes=()=>data.filter(a=>progress[a.one]?.attempts && progress[a.one].lastScore<5);
 const mastered=()=>data.filter(a=>a.group!=='bonus' && progress[a.one]?.streak>=2).length;
 const pool=()=>data.filter(a=>(bonus||a.group!=='bonus')&&(filter==='all'||a.group===filter));
 const shuffle=items=>{const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;};
 function save(){try{localStorage.setItem(key,JSON.stringify(progress));}catch{storageOK=false;}updateCounts();}
 function updateCounts(){ $('#mistake-count').textContent=mistakes().length;$('#storage-state').textContent=storageOK?'每天一點，把結構記牢。':'瀏覽器無法儲存；請匯出紀錄。'; }
 function toast(msg){const el=$('#toast');el.textContent=msg;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',3000);}
 function header(title,sub){return `<div class="page-head"><div><div class="eyebrow">RECALL, DRAW, REMEMBER.</div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="head-mark">H₂N—C<sub>α</sub>—R</div></div>`;}
 function stats(){return `<div class="stats"><div class="stat"><span>已熟記 · 連續兩次全對</span><strong>${mastered()}<small> / 20</small></strong></div><div class="stat"><span>待複習的胺基酸</span><strong>${mistakes().length.toString().padStart(2,'0')}</strong></div><div class="stat"><span>累積完成練習</span><strong>${data.reduce((n,a)=>n+(Number(progress[a.one]?.attempts)||0),0)}</strong></div></div>`;}
 function toolbar(search=false){return `<div class="toolbar"><label><span class="sr-only">胺基酸分類</span><select id="group-filter"><option value="all">全部分類</option>${Object.entries(groups).filter(([k])=>k!=='bonus').map(([k,g])=>`<option value="${k}" ${filter===k?'selected':''}>${g.label}</option>`).join('')}</select></label><label><input id="bonus-toggle" type="checkbox" ${bonus?'checked':''}> 包含加分題</label>${search?'<input class="search push" id="search" aria-label="搜尋胺基酸" placeholder="搜尋名稱、代碼或中文…">':'<span class="muted push">先回想，再看答案。</span>'}</div>`;}
 function bindToolbar(render){$('#group-filter').onchange=e=>{filter=e.target.value;render();};$('#bonus-toggle').onchange=e=>{bonus=e.target.checked;render();};}
 function structure(a){return `<button class="structure" type="button" data-structure="${a.one}" aria-label="放大 ${esc(a.name)} 結構"><img src="assets/structures/${a.one}.svg?v=vector1" alt="${esc(a.name)} ${a.one==='G'?'完整結構':a.one==='P'?'側鏈與主鏈的閉環結構':'R group 結構'}"><span class="structure-zoom">＋ 放大</span></button>`;}
 const structureNote=a=>a.one==='G'?'Glycine 完整兩性離子式：兩個 α 氫皆畫出。':a.one==='P'?'深色為三個 CH₂；灰色 NH 與 Cα 只用來標示接回主鏈的閉環位置。':'灰色 Cα 是主鏈連接位置，不屬於 R group。環上未標字的頂點代表碳，其氫依鍵線式省略。';
 document.addEventListener('click',event=>{const trigger=event.target.closest('[data-structure]');if(!trigger)return;const a=data.find(x=>x.one===trigger.dataset.structure);if(!a)return;const modal=$('#structure-modal');modal.innerHTML=`<div class="structure-modal-head"><div><span class="eyebrow">${a.three} / ${a.one}</span><h2 id="structure-title">${a.name}<small>${a.zh}</small></h2></div><button class="btn" id="close-structure" aria-label="關閉放大結構">關閉 ×</button></div><div class="structure-large"><img src="assets/structures/${a.one}.svg?v=vector1" alt="${esc(a.name)} 放大結構"></div><p class="formula">${a.formula}</p><p class="muted">${structureNote(a)}</p><p class="muted">${a.check}</p>`;$('#close-structure').onclick=()=>modal.close();modal.showModal();});
 $('#structure-modal').addEventListener('click',event=>{if(event.target===$('#structure-modal'))$('#structure-modal').close();});
 function activate(next){if(observer)observer.disconnect();view=next;all('.nav').forEach(el=>el.classList.toggle('active',el.dataset.view===view));if(view==='library')renderLibrary();else if(view==='memory')renderMemory();else if(view==='exam')exam?renderQuestion():renderExamIntro();else startPractice();}
 function memoryContent(a){const m=window.MEMORY[a.one];return `<div class="memory-content"><p class="memory-hook">${esc(m.hook)}</p><div class="memory-chain"><b>${a.three}</b><span>→</span><strong>${a.one}</strong></div><dl class="memory-notes"><dt>名字拆著寫</dt><dd class="spelling">${m.parts.map(esc).join(' · ')}</dd><dt>三字母 ${a.three}</dt><dd>${esc(m.three)}</dd><dt>單字母 ${a.one}</dt><dd>${esc(m.one)}</dd></dl></div>`;}
 function bindPracticeLinks(){all('[data-practice]').forEach(b=>b.onclick=()=>{view='practice';all('.nav').forEach(el=>el.classList.toggle('active',el.dataset.view===view));startPractice(b.dataset.practice);window.scrollTo(0,0);});}
 function renderMemory(){if(observer)observer.disconnect();$('#main').innerHTML=header('給每個名字，一個畫面。','先記最直覺的字首，再用諧音、拆字和圖像，補上容易忘記的代碼。')+`<div class="memory-guide"><div><span class="eyebrow">先記這句</span><h2>酸 D E，醯胺 N Q；<br>短 D N，長 E Q。</h2><p>短、長指側鏈中的 CH₂ 數量：1 個與 2 個。<br>酸以 COO⁻ 結尾，醯胺以 C(=O)NH₂ 結尾。</p></div><div class="memory-table-wrap"><table class="memory-table"><caption>名字、三字母、單字母一起配對</caption><thead><tr><th scope="col">側鏈</th><th scope="col">酸</th><th scope="col">醯胺</th></tr></thead><tbody><tr><th scope="row">短 · 1 個 CH₂</th><td>Aspartic acid<br><b>Asp · D</b></td><td>Asparagine<br><b>Asn · N</b></td></tr><tr><th scope="row">長 · 2 個 CH₂</th><td>Glutamic acid<br><b>Glu · E</b></td><td>Glutamine<br><b>Gln · Q</b></td></tr></tbody></table></div></div><div class="memory-shortcuts"><p><b>芳香族三個畫面</b><br>苯搭飛機 <strong>Phe / F</strong> · 色彩旅行過雙環橋 <strong>Trp / W</strong> · 酪農拿 Y 叉 <strong>Tyr / Y</strong></p><p><b>Leu、Ile、Lys，別混淆</b><br>白 <strong>Leu / L</strong> · 異白 <strong>Ile / I</strong> · 離開拿 Key <strong>Lys / K</strong></p><p><b>11 個可以直接抓字首</b><br><strong>G A V L I M P S T C H</strong><br><span>Gly、Ala、Val、Leu、Ile、Met、Pro、Ser、Thr、Cys、His。先拿下這 11 個，再記剩下 9 個例外。</span></p></div><p class="muted memory-disclaimer">以下為自編聯想，不是命名由來；諧音也不是標準英文發音。考試要寫卡片上的正式拼字。拆字中的「·」只是閱讀分段，作答時不要加上。</p>${toolbar(true)}<div class="toolbar"><button class="btn" id="fold-memory">收起口訣，試著回想</button><span class="muted">看一遍 → 收起 → 說出全名、三字母、單字母 → 點開核對</span></div><div class="memory-grid" id="memory-results"></div>`;bindToolbar(renderMemory);$('#search').oninput=renderMemoryCards;$('#fold-memory').onclick=()=>{const cards=all('.memory-card');const close=cards.some(c=>c.open);cards.forEach(c=>c.open=!close);$('#fold-memory').textContent=close?'展開全部口訣':'收起口訣，試著回想';};renderMemoryCards();}
 function renderMemoryCards(){const term=clean($('#search').value);const list=pool().filter(a=>clean([a.name,a.three,a.one,a.zh,...Object.values(window.MEMORY[a.one]).flat()].join(' ')).includes(term));$('#memory-results').innerHTML=list.length?list.map(a=>`<details class="memory-card" open style="--group:${groups[a.group].color}"><summary><span>${a.zh}<small>${a.name}</small></span><span class="memory-open-label">回想 / 核對</span></summary>${memoryContent(a)}<button class="btn" data-practice="${a.one}">默寫這一題 →</button></details>`).join(''):'<p class="muted">沒有符合的口訣，試試名稱、代碼或聯想關鍵字。</p>';$('#fold-memory').textContent='收起口訣，試著回想';bindPracticeLinks();}
 function startPractice(code){queue=view==='mistakes'?shuffle(mistakes()):shuffle(pool());if(code){queue=[data.find(a=>a.one===code),...queue.filter(a=>a.one!==code)];}index=0;resetQuestion();}
 function resetQuestion(){current=exam?exam.items[exam.pos]:queue[index];revealed=false;graded=false;structureScore=null;strokes=[];redo=[];activeStroke=null;renderQuestion();}
 function renderQuestion(){
  if(observer)observer.disconnect();
  if(!current){$('#main').innerHTML=header(view==='mistakes'?'錯題複習':'默寫練習','把不熟的部分，再練習一次。')+`<div class="panel empty"><h2>${view==='mistakes'?'目前沒有錯題':'這個分類沒有題目'}</h2><p class="muted">${view==='mistakes'?'完成默寫後，未滿 5 分的胺基酸會出現在這裡。':'請選擇其他分類。'}</p><button id="back-practice" class="btn primary">開始默寫練習</button></div>`;$('#back-practice').onclick=()=>activate('practice');return;}
  const a=current,isExam=!!exam;
  $('#main').innerHTML=header(isExam?'模擬小考':view==='mistakes'?'把錯題，變成記得。':'今天，記住幾個？',isExam?'先完成全部默寫，再逐題對照結構與評分。':'寫出名稱、代碼與結構。讓記憶從「看過」變成「寫得出來」。')+(isExam?`<div class="toolbar"><span class="muted">正式題 20 題 × 5 分${exam.bonus?' ＋ 1 題加分練習':''}</span><button class="link-button push" id="exit-exam">結束這次小考</button></div><div class="progress-track"><div style="width:${exam.pos/exam.items.length*100}%"></div></div>`:stats()+(view==='practice'?toolbar():''))+`
   <section class="panel" aria-label="默寫題目"><div class="question-head"><span class="q-index">${isExam?'EXAM':'PRACTICE'} / ${String(isExam?exam.pos+1:index+1).padStart(2,'0')} <span>OF ${isExam?exam.items.length:queue.length}</span></span><span class="pill">${a.one==='G'?'完整結構':a.one==='U'?'BONUS · R group':'R group 結構'}</span></div>
   <div class="work-area"><div class="drawing-side"><div class="prompt"><h2>${a.zh}</h2><span>請寫出${a.one==='G'?'完整結構':'側鏈結構'}</span></div><div class="field-label">${a.one==='G'?'01 / 完整結構':'01 / R group'}<b>2 POINTS</b></div><div class="canvas-wrap">${paper?'<div class="paper-message">在紙上畫好結構，再填寫右側答案。<br>公布答案後，可自行對照評分。</div>':'<canvas id="draw" aria-label="手寫結構畫布，可改用紙筆模式"></canvas><div class="canvas-placeholder"><span>— R</span>在這裡畫下你的答案</div>'}</div><div class="canvas-tools"><button class="link-button" id="undo" ${paper?'disabled':''}>↶ 復原</button><button class="link-button" id="redo" ${paper?'disabled':''}>↷ 重做</button><button class="link-button" id="clear" ${paper?'disabled':''}>清空</button><button class="link-button paper-mode" id="paper">${paper?'切換手寫板':'改用紙筆'}</button></div></div>
   <form class="inputs-side" id="answer-form"><div class="field"><label for="full-name">02 / 英文全名 <span>1 PT</span></label><input id="full-name" placeholder="輸入完整英文名稱" autocomplete="off" autocapitalize="off" spellcheck="false"></div><div class="codes"><div class="field"><label for="three-code">03 / 三字母 <span>1 PT</span></label><input id="three-code" placeholder="Three-letter" autocomplete="off" autocapitalize="off" spellcheck="false"></div><div class="field"><label for="one-code">04 / 單字母 <span>1 PT</span></label><input id="one-code" placeholder="One-letter" autocomplete="off" autocapitalize="off" spellcheck="false"></div></div><p class="answer-tip">${isExam?'空白會算未作答。結構於交卷後自行對照評分。':'想不起來也沒關係。先試著寫，再對照答案找出差異。'}</p><button class="btn primary full" id="reveal" type="submit">${isExam?(exam.pos===exam.items.length-1?'交卷並開始批改':'儲存，前往下一題'):'寫好了，對照答案'} <span>→</span></button></form></div><div class="question-foot"><span>${a.one==='G'?'Glycine 必考完整結構，包含胺基與羧基。':a.one==='P'?'Proline：請把 R group 接回主鏈 N 的關係畫清楚。':'結構 2 分 ＋ 名稱與代碼各 1 分 ＝ 每題 5 分'}</span></div><div id="answer-area" aria-live="polite"></div></section>${isExam?'':'<div class="note-strip"><b>記憶小習慣</b>　先默寫 → 對照差異 → 隔一段時間再寫一次。連續兩次全對，才算熟記。</div>'}`;
  if(!isExam&&view==='practice')bindToolbar(()=>startPractice());
  if(isExam)$('#exit-exam').onclick=()=>{if(confirm('結束小考？這次尚未批改的答案不會列入學習進度。')){exam=null;activate('exam');}};
  $('#answer-form').onsubmit=e=>{e.preventDefault();if(isExam)submitExam();else reveal();};
  $('#paper').onclick=()=>{const values=readValues();const oldStrokes=strokes;paper=!paper;renderQuestion();strokes=oldStrokes;setValues(values);paint();};
  $('#undo').onclick=()=>{if(strokes.length){redo.push(strokes.pop());paint();}};$('#redo').onclick=()=>{if(redo.length){strokes.push(redo.pop());paint();}};$('#clear').onclick=()=>{redo.push(...strokes);strokes=[];paint();};
  setupCanvas();
 }
 function readValues(){return {name:$('#full-name').value,three:$('#three-code').value,one:$('#one-code').value};}
 function setValues(v){$('#full-name').value=v.name;$('#three-code').value=v.three;$('#one-code').value=v.one;}
 function setupCanvas(){canvas=$('#draw');ctx=canvas?.getContext('2d');if(!canvas)return;observer=new ResizeObserver(()=>{const r=canvas.getBoundingClientRect(),d=window.devicePixelRatio||1;canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);paint();});observer.observe(canvas);
  const point=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height];};
  canvas.onpointerdown=e=>{if(revealed)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);activeStroke={id:e.pointerId,points:[point(e)]};strokes.push(activeStroke.points);redo=[];paint();};
  canvas.onpointermove=e=>{if(!activeStroke||activeStroke.id!==e.pointerId)return;activeStroke.points.push(point(e));paint();};
  canvas.onpointerup=canvas.onpointercancel=canvas.onlostpointercapture=()=>{activeStroke=null;};
 }
 function paint(){if(!canvas||!ctx||!canvas.isConnected)return;const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.strokeStyle='#254d59';ctx.fillStyle='#254d59';ctx.lineWidth=2.4;ctx.lineCap='round';ctx.lineJoin='round';strokes.forEach(points=>{if(points.length===1){ctx.beginPath();ctx.arc(points[0][0]*r.width,points[0][1]*r.height,1.2,0,Math.PI*2);ctx.fill();}else{ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x*r.width,y*r.height):ctx.moveTo(x*r.width,y*r.height));ctx.stroke();}});const p=$('.canvas-placeholder');if(p)p.classList.toggle('hidden',strokes.length>0);}
 function checkText(a,v){return [clean(v.name)===clean(a.name),clean(v.three)===clean(a.three),clean(v.one)===clean(a.one)];}
 function reveal(){if(revealed)return;revealed=true;const values=readValues();all('#answer-form input').forEach(el=>el.readOnly=true);$('#reveal').disabled=true;['undo','redo','clear','paper'].forEach(id=>$('#'+id).disabled=true);renderAnswer(current,values,'#answer-area',()=>nextPractice());$('#answer-area').scrollIntoView({block:'start',behavior:'instant'});}
 function renderAnswer(a,v,target,onNext,record){const checks=checkText(a,v),textScore=checks.filter(Boolean).length;
  $(target).innerHTML=`<div class="answer"><div class="answer-grid"><div><div class="field-label">結構對照・向量重繪 <b>${a.one==='G'?'FULL STRUCTURE':'R GROUP'}</b></div>${structure(a)}<p class="formula">${a.formula}</p><p class="muted">${structureNote(a)}</p></div><div><h3>對照你的答案</h3>${[['英文全名',a.name],['三字母',a.three],['單字母',a.one]].map(([label,answer],i)=>`<div class="result-row"><span>${label}<br><strong>${answer}</strong></span><span class="${checks[i]?'correct':'wrong'}">${checks[i]?'✓ 1 分':`✕ 0 分<br>你寫：${esc([v.name,v.three,v.one][i]||'未作答')}`}</span></div>`).join('')}<p class="feedback-tip"><b>結構檢查</b><br>${a.check}</p><p class="muted">手寫結構由你自行評分，系統不會辨識筆跡。</p><div class="grade-buttons" role="group" aria-label="結構自評"><button class="btn" data-grade="0">還不會 · 0</button><button class="btn" data-grade="1">部分正確 · 1</button><button class="btn" data-grade="2">完全正確 · 2</button></div></div></div><div class="note-strip"><b>結構記憶線索</b>　${a.tip}</div><details class="answer-memory" open><summary>名字與代碼，這樣記</summary>${memoryContent(a)}</details><div class="actions"><span class="muted" id="score-message">選擇結構分數，完成本題批改。</span><button id="next" class="btn primary" disabled>${exam?'確認分數，下一步':'儲存分數，下一題'} →</button></div></div>`;
  all('[data-grade]',$(target)).forEach(btn=>btn.onclick=()=>{structureScore=Number(btn.dataset.grade);all('[data-grade]',$(target)).forEach(b=>b.classList.toggle('selected',b===btn));$('#score-message').innerHTML=`本題得分 <strong>${textScore+structureScore}</strong> / 5`;$('#next').disabled=false;});
  $('#next').onclick=()=>{if(graded||structureScore===null)return;graded=true;const score=textScore+structureScore;recordScore(a,score);if(record){record.score=score;record.structureScore=structureScore;}onNext();};
 }
 function recordScore(a,score){const old=progress[a.one]||{};progress[a.one]={attempts:(Number(old.attempts)||0)+1,streak:score===5?(Number(old.streak)||0)+1:0,lastScore:score,lastSeen:new Date().toISOString()};save();}
 function nextPractice(){index++;if(index>=queue.length){if(view==='mistakes'){queue=shuffle(mistakes());index=0;}else{queue=shuffle(pool());index=0;}toast('這一輪完成！繼續鞏固記憶。');}resetQuestion();window.scrollTo(0,0);}
 function renderLibrary(){if(observer)observer.disconnect();$('#main').innerHTML=header('把 20 種結構，看出規律。','先按側鏈分類，再比較只差一個原子或一個 CH₂ 的胺基酸。')+toolbar(true)+`<div class="compare"><h3>容易混淆的四組</h3><p><b>Val / Leu / Ile</b>　比較分枝位置：立即分枝 / 隔一個 CH₂ / 立即分枝但兩枝不同長。</p><p><b>Asp / Asn · Glu / Gln</b>　酸的末端是 COO⁻；醯胺的末端是 C(=O)NH₂。Gl- 比 As- 多一個 CH₂。</p><p><b>Ser / Cys / Sec</b>　同一段 CH₂ 後面：OH / SH / SeH。</p><p><b>Phe / Tyr</b>　同樣先接 CH₂ 與苯環；Tyr 在苯環對位多一個 OH。</p></div><p class="muted">圖例：灰色 Cα 是主鏈連接點，不屬於 R group；Proline 的灰色 NH 用來標示閉環。環上未標字的頂點是碳，其氫依鍵線式省略。點圖可放大。</p><div id="library-results" class="library-grid"></div>`;bindToolbar(renderLibrary);$('#search').oninput=renderCards;renderCards();}
 function renderCards(){const term=clean($('#search').value);const list=pool().filter(a=>clean([a.name,a.three,a.one,a.zh,a.formula].join(' ')).includes(term));$('#library-results').innerHTML=list.length?list.map(a=>`<article class="amino-card" style="--group:${groups[a.group].color}"><div class="card-top"><span>${groups[a.group].label}</span><strong>${a.one}</strong></div><h3>${a.name}</h3><span class="chinese">${a.zh} · ${a.three}${a.one==='G'?' · 必考完整結構':''}</span>${structure(a)}<p class="formula">${a.formula}</p><details><summary>名字口訣、代碼與結構檢查</summary>${memoryContent(a)}<p>${a.tip}</p><p>${a.check}</p></details><button class="btn" data-practice="${a.one}">默寫這一題 →</button></article>`).join(''):'<p class="muted">找不到符合的胺基酸，試試英文名稱或代碼。</p>';all('[data-practice]').forEach(b=>b.onclick=()=>{view='practice';all('.nav').forEach(el=>el.classList.toggle('active',el.dataset.view===view));startPractice(b.dataset.practice);window.scrollTo(0,0);});}
 function renderExamIntro(){$('#main').innerHTML=header('模擬小考','按照課堂配分，完整默寫一輪。')+`<section class="panel exam-intro"><span class="pill">QUIZ / 20 AMINO ACIDS</span><h2 style="margin-top:20px">每一題，從零寫出來。</h2><p class="muted">以中文名稱出題，隨機排列 20 種胺基酸。Glycine 畫完整結構，其餘畫 R group。完成全部題目後，才顯示答案。</p><div class="exam-rules"><div><b>2</b><span>結構</span></div><div><b>1</b><span>英文全名</span></div><div><b>1</b><span>Three-letter</span></div><div><b>1</b><span>One-letter</span></div></div><p class="muted">20 題滿分 100。英文自動比對，忽略大小寫與多餘空白；全名依講義用 Aspartic acid、Glutamic acid。手寫結構自行給 0–2 分，結果屬自評練習分數。</p><label class="checkline"><input id="exam-bonus" type="checkbox"> 加入 Selenocysteine 加分練習</label><p class="muted">加分題另列 0–5 分練習成績，不自行推算老師的 bonus 配分。小考需在本次頁面中完成，重新整理不會保留作答。</p><button class="btn primary" id="start-exam">開始 20 題小考 →</button></section>`;$('#start-exam').onclick=()=>{const withBonus=$('#exam-bonus').checked;exam={items:[...shuffle(data.filter(a=>a.group!=='bonus')),...(withBonus?[data[20]]:[])],bonus:withBonus,pos:0,records:[],review:0};resetQuestion();};}
 function submitExam(){exam.records.push({amino:current,values:readValues(),strokes:strokes.map(s=>s.map(p=>[...p])),paper});exam.pos++;if(exam.pos<exam.items.length)resetQuestion();else renderExamReview();window.scrollTo(0,0);}
 function renderExamReview(){if(observer)observer.disconnect();const record=exam.records[exam.review];graded=false;structureScore=null;revealed=true;$('#main').innerHTML=header('交卷了，對照每一筆。',`批改第 ${exam.review+1} / ${exam.records.length} 題 · ${record.amino.zh}`)+`<div class="panel"><div class="drawing-side"><h3>你的結構作答</h3>${record.paper?'<p class="muted">請拿出紙上作答，與下方重繪結構比較。</p>':'<div class="canvas-wrap"><canvas id="draw" aria-label="本題提交的手寫結構"></canvas></div>'}</div><div id="review-answer"></div></div>`;strokes=record.strokes;setupCanvas();renderAnswer(record.amino,record.values,'#review-answer',()=>{exam.review++;if(exam.review<exam.records.length)renderExamReview();else renderSummary();window.scrollTo(0,0);},record);}
 function renderSummary(){const total=exam.records.filter(r=>r.amino.group!=='bonus').reduce((n,r)=>n+r.score,0),extra=exam.records.find(r=>r.amino.group==='bonus');$('#main').innerHTML=header('這一輪，完成了。','分數包含結構自評。現在把容易混淆的部分再寫一次。')+`<section class="panel summary-panel"><span class="eyebrow">YOUR RECALL SCORE</span><div class="score-big">${total}<small> / 100</small></div>${extra?`<p>加分題練習：${extra.score} / 5（另計）</p>`:''}<p class="muted">${exam.records.filter(r=>r.score===5).length} 題完全正確 · 未滿分題目已加入錯題複習</p><div class="summary-list">${exam.records.map(r=>`<div class="result-row"><span>${r.amino.name} · ${r.amino.three} · ${r.amino.one}</span><strong class="${r.score===5?'correct':'wrong'}">${r.score} / 5</strong></div>`).join('')}</div><button class="btn primary" id="review-mistakes">複習錯題 →</button> <button class="btn" id="retry-exam">再考一次</button></section>`;exam=null;$('#review-mistakes').onclick=()=>activate('mistakes');$('#retry-exam').onclick=renderExamIntro;}
 all('.nav').forEach(el=>el.onclick=()=>{if(exam){if(!confirm('離開小考？尚未批改的作答會遺失，已批改的題目會保留在學習進度。'))return;exam=null;}activate(el.dataset.view);});
 $('#export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),progress},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='amino-lab-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('學習紀錄已匯出。');};
 window.addEventListener('beforeunload',e=>{if(exam){e.preventDefault();e.returnValue='';}});
 updateCounts();queue=[...data.slice(0,20)];resetQuestion();
})();
